### ISSUE TITLE
Error at getTransactionFromAddress(...)

### ISSUE THREAD

**Issue by nugaon** [TRON-US/tronweb#25]
I've got an error from the lib when I would like to retrieve the transactions of an account.

```ts
const sendedTransactions = await this.client.trx.getTransactionsFromAddress(account, offset, page);
```
The error:
```text
Debug: internal, implementation, error 
  TypeError: Cannot read property 'transaction' of null
  at address (/home/ubuntu/bicyclechain/node_modules/tronweb/dist/webpack:/src/lib/trx.js:278:17)
 at process._tickCallback (internal/process/next_tick.js:68:7)
```
I have synced FullNode and SolidityNode also. From my SolidityNode's config would be important the index.switch = "off".

**Comment by UnforgivenZZZ** [comment]
if you are using java-tron's walletextension api, it has to be turned on
